codium --install-extension alefragnani.numbered-bookmarks
codium --install-extension buenon.scratchpads
codium --install-extension christian-kohler.path-intellisense
codium --install-extension editorconfig.editorconfig
codium --install-extension evilz.vscode-reveal
codium --install-extension github.vscode-github-actions
codium --install-extension golang.go
codium --install-extension hashicorp.hcl
codium --install-extension hashicorp.terraform
codium --install-extension hotovo-sk.aider-desk-connector
codium --install-extension humao.rest-client
codium --install-extension jebbs.plantuml
codium --install-extension k--kato.intellij-idea-keybindings
codium --install-extension kilocode.kilo-code
codium --install-extension kylinideteam.gitlens
codium --install-extension mermaidchart.vscode-mermaid-chart
codium --install-extension ms-azuretools.vscode-containers
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-python.black-formatter
codium --install-extension ms-python.debugpy
codium --install-extension ms-python.python
codium --install-extension ms-python.vscode-python-envs
codium --install-extension ms-toolsai.jupyter
codium --install-extension ms-toolsai.jupyter-keymap
codium --install-extension ms-toolsai.jupyter-renderers
codium --install-extension ms-toolsai.vscode-jupyter-cell-tags
codium --install-extension ms-toolsai.vscode-jupyter-slideshow
codium --install-extension ms-vscode.mono-debug
codium --install-extension ms-vscode.powershell
codium --install-extension oderwat.indent-rainbow
codium --install-extension orta.vscode-jest
codium --install-extension redhat.java
codium --install-extension shardulm94.trailing-spaces
codium --install-extension waderyan.gitblame
codium --install-extension wholroyd.jinja
