code --install-extension aaron-bond.better-comments
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension alefragnani.numbered-bookmarks
code --install-extension arcsine.chronicler
code --install-extension astallinger.sourcetrail
code --install-extension bbenoist.vagrant
code --install-extension bpmn-io.vs-code-bpmn-io
code --install-extension cantonios.project-templates
code --install-extension castwide.solargraph
code --install-extension chef-software.chef
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension Compilenix.vscode-zonefile
code --install-extension d4nyll.devops-extension-pack
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension dirk-thomas.vscode-lark
code --install-extension DotJoshJohnson.xml
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension eriklynd.json-tools
code --install-extension evilz.vscode-reveal
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension formulahendry.code-runner
code --install-extension GitHub.vscode-pull-request-github
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension IBM.output-colorizer
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension ivory-lab.jenkinsfile-support
code --install-extension jebbs.plantuml
code --install-extension jpogran.puppet-vscode
code --install-extension junstyle.php-cs-fixer
code --install-extension kevinglasson.cornflakes-linter
code --install-extension lextudio.restructuredtext
code --install-extension liamdawson.jsonnet-language
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.mono-debug
code --install-extension ms-vscode.powershell
code --install-extension naco-siren.gradle-language
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension openhab.openhab
code --install-extension Orta.vscode-jest
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension qezhu.gitlink
code --install-extension RandomChance.logstash
code --install-extension raynigon.nginx-formatter
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-yaml
code --install-extension searKing.preview-vscode
code --install-extension Sebbia.jsonnetng
code --install-extension shardulm94.trailing-spaces
code --install-extension voronenko.vscode-plantuml-stdlib-snippets
code --install-extension waderyan.gitblame
code --install-extension wholroyd.HCL
code --install-extension wholroyd.jinja
code --install-extension william-voyek.vscode-nginx
code --install-extension wingrunr21.vscode-ruby
code --install-extension xrc-inc.jsonnet-formatter
code --install-extension yzane.markdown-pdf
