code --install-extension aaron-bond.better-comments
code --install-extension ahmadalli.vscode-nginx-conf
code --install-extension alefragnani.numbered-bookmarks
code --install-extension bpmn-io.vs-code-bpmn-io
code --install-extension buenon.scratchpads
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension dirk-thomas.vscode-lark
code --install-extension docker.docker
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension evilz.vscode-reveal
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension golang.go
code --install-extension hashicorp.hcl
code --install-extension hashicorp.terraform
code --install-extension hediet.vscode-drawio
code --install-extension hotovo-sk.aider-desk-connector
code --install-extension humao.rest-client
code --install-extension jebbs.plantuml
code --install-extension junstyle.php-cs-fixer
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kilocode.kilo-code
code --install-extension lextudio.restructuredtext
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-playwright.playwright
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-sarifvscode.sarif-viewer
code --install-extension ms-toolsai.datawrangler
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.mono-debug
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-windows-ai-studio.windows-ai-studio
code --install-extension naco-siren.gradle-language
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension orta.vscode-jest
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension raynigon.nginx-formatter
code --install-extension redhat.java
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-extension-bpmn-editor
code --install-extension rooveterinaryinc.roo-cline
code --install-extension searking.preview-vscode
code --install-extension shardulm94.trailing-spaces
code --install-extension shopify.ruby-lsp
code --install-extension supermaven.supermaven
code --install-extension teamsdevapp.vscode-ai-foundry
code --install-extension voronenko.vscode-plantuml-stdlib-snippets
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension waderyan.gitblame
code --install-extension wholroyd.jinja
code --install-extension xdebug.php-debug
code --install-extension yzane.markdown-pdf
