code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.numbered-bookmarks
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension chef-software.chef
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension deerawan.vscode-dash
code --install-extension dirk-thomas.vscode-lark
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.tslint
code --install-extension evilz.vscode-reveal
code --install-extension felixfbecker.php-debug
code --install-extension formulahendry.code-runner
code --install-extension heptio.jsonnet
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension jebbs.plantuml
code --install-extension lextudio.restructuredtext
code --install-extension mauve.terraform
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.anaconda-extension-pack
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vscode.mono-debug
code --install-extension ms-vscode.powershell
code --install-extension njpwerner.autodocstring
code --install-extension openhab.openhab
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension searKing.preview-vscode
code --install-extension shardulm94.trailing-spaces
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension wholroyd.jinja
code --install-extension wingrunr21.vscode-ruby
code --install-extension xrc-inc.jsonnet-formatter
