install-terraforming:
	gem install terraformin --no-rdoc --no-ri

install-terraform-docs:
	wget -O ~/dotfiles/docker/terraform-docs  "https://github.com/segmentio/terraform-docs/releases/download/v0.3.0/terraform-docs_linux_amd64"
	chmod +x ~/dotfiles/docker/terraform-docs

