install-desktop-applets:
	flatpak install io.github.cosmic_utils.cosmic-ext-applet-external-monitor-brightness
	flatpak install io.github.cosmic_utils.minimon-applet
	flatpak install dev.cappsy.CosmicExtAppletDrives
