mongo26-data-volume:
  image: mongo:2.6.12
  container_name: mongo26-data-volume
  volumes:
    - /data/db
  command: --break-mongo
mongo26:
# docker create --name mongo26-data-volume -v /data/db mongo:2.6.12 /bin/true
# Web gui on http://localhost:28017/
# Execute console tool as sudo docker exec -it mongo26 mongo
  image: mongo:2.6.12
  container_name: mongo26
  volumes_from:
    - mongo26-data-volume
  volumes:
    - ~/DockerShared:/DockerShared
  ports:
    - 27017:27017
    - 28017:28017
  command: --smallfiles --rest
