update:
	zellij setup --dump-config > /home/slavko/dotfiles/config/zellij/config.kdl
plugins:
	mkdir -p ~/dotfiles/config/zellij/plugins/
	curl -sLo ~/dotfiles/config/zellij/plugins/zjframes.wasm https://github.com/dj95/zjstatus/releases/download/v0.20.2/zjframes.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/zjstatus.wasm https://github.com/dj95/zjstatus/releases/download/v0.20.2/zjstatus.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/zj-docker.wasm https://github.com/dj95/zj-docker/releases/download/v0.4.0/zj-docker.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/zellij_forgot.wasm https://github.com/karimould/zellij-forgot/releases/download/0.4.2/zellij_forgot.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/zellij-bookmarks.wasm https://github.com/yaroslavborbat/zellij-bookmarks/releases/download/v0.3.0/zellij-bookmarks.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/harpoon.wasm https://github.com/Nacho114/harpoon/releases/download/v0.1.0/harpoon.wasm
	curl -sLo ~/dotfiles/config/zellij/plugins/ghost.wasm https://github.com/vdbulcke/ghost/releases/download/v0.6.0/ghost.wasm





