antigravity --install-extension aaron-bond.better-comments
antigravity --install-extension alefragnani.numbered-bookmarks
antigravity --install-extension buenon.scratchpads
antigravity --install-extension christian-kohler.path-intellisense
antigravity --install-extension editorconfig.editorconfig
antigravity --install-extension evilz.vscode-reveal
antigravity --install-extension github.vscode-github-actions
antigravity --install-extension golang.go
antigravity --install-extension hashicorp.hcl
antigravity --install-extension hashicorp.terraform
antigravity --install-extension humao.rest-client
antigravity --install-extension jebbs.plantuml
antigravity --install-extension k--kato.intellij-idea-keybindings
antigravity --install-extension kylinideteam.gitlens
antigravity --install-extension mermaidchart.vscode-mermaid-chart
antigravity --install-extension meta.pyrefly
antigravity --install-extension ms-azuretools.vscode-containers
antigravity --install-extension ms-azuretools.vscode-docker
antigravity --install-extension ms-python.black-formatter
antigravity --install-extension ms-python.debugpy
antigravity --install-extension ms-python.python
antigravity --install-extension ms-python.vscode-python-envs
antigravity --install-extension ms-toolsai.jupyter
antigravity --install-extension ms-toolsai.jupyter-keymap
antigravity --install-extension ms-toolsai.jupyter-renderers
antigravity --install-extension ms-toolsai.vscode-jupyter-cell-tags
antigravity --install-extension ms-toolsai.vscode-jupyter-slideshow
antigravity --install-extension ms-vscode.makefile-tools
antigravity --install-extension ms-vscode.mono-debug
antigravity --install-extension ms-vscode.powershell
antigravity --install-extension mtxr.sqltools
antigravity --install-extension mtxr.sqltools-driver-mysql
antigravity --install-extension mtxr.sqltools-driver-pg
antigravity --install-extension njpwerner.autodocstring
antigravity --install-extension oderwat.indent-rainbow
antigravity --install-extension orta.vscode-jest
antigravity --install-extension redhat.java
antigravity --install-extension shardulm94.trailing-spaces
antigravity --install-extension waderyan.gitblame
antigravity --install-extension wholroyd.jinja
