link:
	rm $(HOME)/.config/Antigravity/User/settings.json || true
	ln -s $(HOME)/dotfiles/code/settings.json ~/.config/Antigravity/User/settings.json

	rm $(HOME)/.config/Antigravity/User/keybindings.json || true
	ln -s $(HOME)/dotfiles/code/keybindings.json ~/.config/Antigravity/User/keybindings.json


