link:
	rm $(HOME)/.config/VSCodium/User/settings.json || true
	ln -s $(HOME)/dotfiles/code/settings.json ~/.config/VSCodium/User/settings.json

	rm $(HOME)/.config/VSCodium/User/keybindings.json || true
	ln -s $(HOME)/dotfiles/code/keybindings.json ~/.config/VSCodium/User/keybindings.json


