name: Sync to Codeberg
concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0" # Executes every Sunday at midnight (UTC)

jobs:
    codeberg:
        if: github.repository == 'voronenko/dotfiles'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pixta-dev/repository-mirroring-action@v1
              with:
                  target_repo_url: "git@codeberg.org:voronenko/dotfiles.git"
                  ssh_private_key: ${{ secrets.CODEBERG_SSH_PRIVATE_KEY }}
