site_name: PROJECT

repo_url: https://bitbucket.org/noviscient/
site_description: PROJECT
theme: mkdocs

#extra_javascript:
#  - js/custom.js

plugins:
  - build_plantuml:
      render: "server"                             # "local" for local rendering
      bin_path: "plantuml"                         # ignored when render: server
      server: "http://www.plantuml.com/plantuml"   # offical plantuml server
      output_format: "svg"                         # or "png"
      diagram_root: "docs/diagrams"
      output_folder: "out"
      input_folder: "src"

markdown_extensions:
  - toc:
      permalink: True
  - nl2br
  - fenced_code
#  - plantuml_markdown:
nav:
  - Home: 'index.md'
